### ISSUE TITLE
marshal data too short

### ISSUE THREAD

**Issue by sebasjimenez10** [piotrmurach/rspec-benchmark#1]
Hello,

I came across this issue while writing a test:

```
ArgumentError:
       marshal data too short
     # /Users/sebastianjimenez/.rvm/gems/ruby-2.3.1@business-tool/gems/activesupport-4.2.7.1/lib/active_support/core_ext/marshal.rb:6:in `load'
     # /Users/sebastianjimenez/.rvm/gems/ruby-2.3.1@business-tool/gems/activesupport-4.2.7.1/lib/active_support/core_ext/marshal.rb:6:in `load_with_autoloading'
     # /Users/sebastianjimenez/.rvm/gems/ruby-2.3.1@business-tool/gems/benchmark-perf-0.1.0/lib/benchmark/perf/execution_time.rb:64:in `run_in_subprocess'
     # /Users/sebastianjimenez/.rvm/gems/ruby-2.3.1@business-tool/gems/benchmark-perf-0.1.0/lib/benchmark/perf/execution_time.rb:98:in `block in run'
     # /Users/sebastianjimenez/.rvm/gems/ruby-2.3.1@business-tool/gems/activesupport-4.2.7.1/lib/active_support/core_ext/range/each.rb:7:in `each'
     # /Users/sebastianjimenez/.rvm/gems/ruby-2.3.1@business-tool/gems/activesupport-4.2.7.1/lib/active_support/core_ext/range/each.rb:7:in `each_with_time_with_zone'
     # /Users/sebastianjimenez/.rvm/gems/ruby-2.3.1@business-tool/gems/benchmark-perf-0.1.0/lib/benchmark/perf/execution_time.rb:95:in `run'
     # /Users/sebastianjimenez/.rvm/gems/ruby-2.3.1@business-tool/gems/rspec-benchmark-0.1.0/lib/rspec/benchmark/timing_matcher.rb:38:in `matches?'
     # /Users/sebastianjimenez/.rvm/gems/ruby-2.3.1@business-tool/gems/rspec-expectations-3.5.0/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
     # /Users/sebastianjimenez/.rvm/gems/ruby-2.3.1@business-tool/gems/rspec-expectations-3.5.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # /Users/sebastianjimenez/.rvm/gems/ruby-2.3.1@business-tool/gems/rspec-expectations-3.5.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # /Users/sebastianjimenez/.rvm/gems/ruby-2.3.1@business-tool/gems/rspec-expectations-3.5.0/lib/rspec/expectations/expectation_target.rb:65:in `to'
     # /Users/sebastianjimenez/.rvm/gems/ruby-2.3.1@business-tool/gems/rspec-expectations-3.5.0/lib/rspec/expectations/expectation_target.rb:101:in `to'
```

Basically I'm passing a block where I'm calling the method I want to benchmark like this:

```
it "should perform under 1 sec" do
  expect { subject.pricing }.to perform_under(1).sec
end
```

Is there anything I'm missing?

Thanks in advance

**Comment by piotrmurach** [comment]
Hey Sebastian,

Thanks for using the library!

The time benchmarking matcher relies under covers on [benchmark-perf](https://github.com/piotrmurach/benchmark-perf). It uses `Marshal` for passing time execution between processes. Nothing really fancy. However, I have a feeling that `active_support` maybe redefining how it works and causing it to crash. Quick search on the internet suggest that few people come across this failure in Rails projects.

Is there anyway you can replicate the problem without using activesupport with some simple code? Otherwise I will struggle fixing this issue.

**Comment by sebasjimenez10** [comment]
@piotrmurach Thanks for the quick reply!

Unfortunately, since I'm using rspec under a rails project I honestly don't see a way to "skip" active support intervention. But I can help you out fixing the issue 😄

**Comment by piotrmurach** [comment]
I guess I'd first try to see if the block is correctly evaluated for some simple ruby as I don't know what happens inside of `subject.pricing` to check if the block works fine inside Rails.
```ruby
expect { 'x' * 100000 }.to perform_under(1).sec
```

**Comment by sebasjimenez10** [comment]
You were right, with the example you provided the test passes. Now, the method I'm calling simply returns a hash of objects that could be complex, but it is still a hash, any other ideas? Thanks for all the help!

**Comment by piotrmurach** [comment]
I have released `v0.1.1` of `benchmark-perf` dependency. Please remove both `rspec-benchmark` and `benchmark-perf` and install again. I'm relying more on Marshal api now, however I don't believe this will change much it terms of resolving the issues but at least it should point if the error comes from this library. Unfortunately I'd still need to see the body of the method you are calling to make any more educated guesses.

**Comment by sebasjimenez10** [comment]
Thank you! I'll proceed and re-install those dependencies and will do further investigation to come up with a more structured context.

**Comment by sebasjimenez10** [comment]
@piotrmurach Thanks for all your help I was able to figure the issue out and the test is being benchmarked correctly! Thanks a lot!

**Comment by piotrmurach** [comment]
Nice one. What was the issue if you don't mind me asking? Is there anything you could contribute to the documentation to warn future users, especially testing in Rails?

**Comment by sebasjimenez10** [comment]
@piotrmurach  I don't mind at all 😄 

My problem was related to rails validations, inside the method I was testing some validations where being executed and every time I executed it, it ended up in a failed validation. What's interesting though is that it wouldn't stop the execution right away, instead it allowed the program to keep running.

Basically I imagine that no data was actually reaching this point: `marshal.rb:6:in `load'`.

I can only think of a little advice and it would be to make sure no exceptions are getting thrown inside the particular method because it seems it would swallow the exception and continue running the program.

**Comment by piotrmurach** [comment]
This is very interesting! So basically the exception trace is for error that happened down the line but not for the original cause. I will investigate this and see what happens when error condition is raised inside the block as I don't think it is great for the matcher to swallow up any exceptions and hence keep timing broken code.

**Comment by sebasjimenez10** [comment]
Yeah that'd be great to stop the execution once an exception takes place! Let me know if I can be of any help.

**Comment by piotrmurach** [comment]
Hey, just released `v0.2.0` that correctly propagates the error and kills the matcher. Please could you try it out on your previous example with the broken validation. I would be keen to know that all works as expected(no pun intended:smile:)

**Comment by sebasjimenez10** [comment]
That's great news, will give it a shot! Thanks!

**Comment by sebasjimenez10** [comment]
@piotrmurach Just confirmed and the exception backtrace shows now the appropriate exception! Thanks! Truly appraciate it 😄

**Comment by piotrmurach** [comment]
🎉  Great! Thanks for checking.
