### ISSUE TITLE
Implement a `perform_allocation_under` matcher

### ISSUE THREAD

**Issue by julianrubisch** [piotrmurach/rspec-benchmark#14]
Hi Piotr, thanks for this awesome tool. I have a little feature request though.

I'm profiling the memory allocation of Rails view partials, and I'd like to be able to state in a spec that a partial must not allocate more than X objects - mainly to track when anyone adds code that massively increases allocations.

Is there a way to do this currently, or would you have to implement another matcher?

**Comment by piotrmurach** [comment]
Hi Julian,

Thanks for using this gem!

The `perform_allocation` matcher uses the number of allocations as the upper boundary already. So your scenario should work, if it doesn't please let me know. Exact match wouldn't be very useful, only in very limited scenarios and would potentially lead to brittle tests as different Ruby versions change internally how many objects are allocated for some operations.

 I will update the documentation to explain this better.

**Comment by julianrubisch** [comment]
That’s what I suspected. 

Maybe add an alias that clarifies this?

**Comment by piotrmurach** [comment]
I could add an alias, but I don't want to bloat API with additional methods. If you have a minute I'd appreciate doc's changes to explain this better.
