### ISSUE TITLE
LocalJumpError: no block given (yield)

### ISSUE THREAD

**Issue by danielmyasnikov** [piotrmurach/rspec-benchmark#16]
### Describe the problem
`Warmup` and `within` helpers do not work
```
expect { create(:assigned_tag) }.to perform_faster_than.within(0.4).warmup(0.2) { AssignedTag.create }
# => LocalJumpError: no block given (yield)
# => from /bundle/gems/benchmark-perf-0.6.0/lib/benchmark/perf/iteration.rb:25:in `call_times'
```

### Expected behaviour
to warm up CPU and execute the test without errors

### Describe your environment

* OS version: Mac OS 10.15.6
* Ruby version: 2.6.3
* RSpec version: 4.0.1
* RSpec::Benchmark version: 0.6.0

**Comment by piotrmurach** [comment]
Hi Daniel 👋 

Thanks for using this gem and submitting this issue.

I was initially surprised to learn that this doesn't work as I used it many times before. On a second look, I realised that the documentation is wrong! This should be:

```ruby
expect { create(:assigned_tag) }.to perform_faster_than { AssignedTag.create }.within(0.4).warmup(0.2)
``` 

All the other matcher examples are correct to call `within` and `warmup` after the matcher.

Alternatively, the `perform_faster_than` matcher can accept parameters:

```ruby
expect { create(:assigned_tag)  }.to perform_faster_than(time: 0.4, warmup: 0.2) { AssignedTag.create }
```
