### ISSUE TITLE
Database content empty for second run

### ISSUE THREAD

**Issue by 5minpause** [piotrmurach/rspec-benchmark#6]
Hi, please close this issue if this is something obvious too everyone but me.

I added the gem to my Rails app trying to benchmark some recursive updates to my records.
I setup everything and it worked. Then I created records in my database for the recursive update.
I created the `expect { foo.bar }.to perform_under(1).sec.and_sample(2)` expectation. (I wanted to start slowly to establish a baseline from where to measure and improve.)

I noticed that the database was cleaned on the second sample and the recursive updates couldn't be run. I couldn't fid anything in your Readme or see where in the code this happens.

Did I do something wrong?
When I create the records *inside* the performance expectations block, it works.

Does that make sense? Should I show you with some pseudo code what my test looked like?

**Comment by piotrmurach** [comment]
Hi,

Thanks for using this gem!

This gem should have no impact on how your records are saved. It has no dependency on external environment such as Rails, databases etc... It simply calls a block, the expectation, a number of times and each time it executes the block it measures the time. Therefore, the implication is that if you setup your DB once before the expectation is executed, and your `foo.bar` code has side effects including modifications to DB, then it is no surprise that it fails to execute correctly on the second block evaluation.

The rspec matchers perform no mutation of your database as they have no understanding of any of your code. This gem can be used in any context to execute a function. If the function is pure then you don't need to worry, however in your case you have clear DB mutations and hence keeping all the setup in the block is the only way to ensure that each block evaluation starts in the same state.

Hope this makes sense!

**Comment by tjwallace** [comment]
I'm having a similar problem. Could it be because [the `benchmark-perf` gem runs the block to be timed in a sub process](https://github.com/piotrmurach/benchmark-perf/blob/b9b553cf0e3d32b7248118dc0afb5883b8f03b16/lib/benchmark/perf/execution_time.rb#L17-L54)?

**Comment by piotrmurach** [comment]
@tjwallace It could be or it could not be, I don't know. Would you have time to code up a minimal example using active record and sqlite that replicates the problem you're having and open a new issue? I would like to have something to poke around and I'm sure we can get to the bottom of it.

**Comment by tjwallace** [comment]
@piotrmurach done, see issue #10

**Comment by piotrmurach** [comment]
@tjwallace Magic! Thank you.

**Comment by 5minpause** [comment]
Thank you @tjwallace
